### ISSUE TITLE
Unsupported expression in static initializer

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#21]
https://gist.github.com/brooksdavis/2654b1e762bf8a82ec88

```
/home/bed22/git/llvm-cheri/Build/bin/clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -mabi=sandbox  -O -pipe -G0   -DMAGIC='"/usr/share/misc/magic"' -DHAVE_CONFIG_H -I/home/bed22/git/cheribsd/lib/libmagic -I/home/bed22/git/cheribsd/lib/libmagic/../../contrib/file/src  -std=gnu99 -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-uninitialized -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Qunused-arguments -c /home/bed22/git/cheribsd/lib/libmagic/../../contrib/file/src/compress.c -o compress.o
fatal error: error in backend: Unsupported expression in static initializer:
      addrspacecast (i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str8, i64 0,
      i64 0) to i8 addrspace(200)*)
clang-3.6: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 3.7.0 (https://github.com/llvm-mirror/clang.git 130f82c3373e3c728766025bd86d53cac22ba210) (https://github.com/llvm-mirror/llvm.git 1dc272f161841baef9f62af3e810a5cc68c9e1ae)
Target: cheri-unknown-freebsd
Thread model: posix
clang-3.6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.6: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.6: note: diagnostic msg: /tmp/compress-e8c8b2.c
clang-3.6: note: diagnostic msg: /tmp/compress-e8c8b2.sh
clang-3.6: note: diagnostic msg: 

********************
*** Error code 70

Stop.
make[3]: stopped in /home/bed22/git/cheribsd/lib/libmagic
*** Error code 1
```

**Comment by davidchisnall** [comment]
This compiles fine for me, I suspect that it was fixed by the last fix.

**Comment by brooksdavis** [comment]
Still broken for me.  Here's a fresh gist in case anything has changed https://gist.github.com/brooksdavis/04226155bfabd56cf394
